#!/usr/bin/env python3
"""Convert GIF to ZMK nice!view animation using Atkinson dithering.

Based on Furglitch/zmk-niceview gif-convert.py (MIT License).
Adapted for eyelash_sofle: default output → boards/shields/eyelash_sofle_animation/assets/

Usage:
    python3 scripts/gif-convert.py input.gif --no-register -W 160 -H 68 \
        -o boards/shields/eyelash_sofle_animation/assets/

    Then update boards/shields/eyelash_sofle_animation/CMakeLists.txt to
    include your new .c file instead of placeholder.c, and update the
    #include in custom_status_screen.c to your new .h file.
"""

import argparse
import os
import re
import subprocess
import tempfile
from PIL import Image, ImageOps

# Default paths relative to this script's location
DEFAULT_ASSETS_DIR = "boards/shields/eyelash_sofle_animation/assets"
# Auto-register targets — leave empty; always use --no-register
DEFAULT_CMAKE_PATH = ""
DEFAULT_KCONFIG_PATH = ""
DEFAULT_ANIMATION_PATH = ""


def atkinson_dither(image, threshold=128):
    """Apply Atkinson dithering to a grayscale image."""
    pixels = image.load()
    width, height = image.size

    for y in range(height):
        for x in range(width):
            old_pixel = pixels[x, y]
            new_pixel = 255 if old_pixel > threshold else 0
            pixels[x, y] = new_pixel

            error = old_pixel - new_pixel

            # Distribute error to neighboring pixels (Atkinson pattern)
            # 1/8 error to each of 4 neighbors
            if x + 1 < width:
                pixels[x + 1, y] = min(255, max(0, pixels[x + 1, y] + error // 8))
            if x + 2 < width:
                pixels[x + 2, y] = min(255, max(0, pixels[x + 2, y] + error // 8))
            if y + 1 < height:
                if x > 0:
                    pixels[x - 1, y + 1] = min(255, max(0, pixels[x - 1, y + 1] + error // 8))
                pixels[x, y + 1] = min(255, max(0, pixels[x, y + 1] + error // 8))
                if x + 1 < width:
                    pixels[x + 1, y + 1] = min(255, max(0, pixels[x + 1, y + 1] + error // 8))
            if y + 2 < height:
                pixels[x, y + 2] = min(255, max(0, pixels[x, y + 2] + error // 8))

    return image


def process_frame(frame, target_width, target_height, threshold=128):
    """Process a frame with Atkinson dithering."""

    # Resize to fit within target dimensions
    original_width, original_height = frame.size
    scale = min(target_width / original_width, target_height / original_height)
    new_width = int(original_width * scale)
    new_height = int(original_height * scale)
    resized = frame.resize((new_width, new_height), Image.LANCZOS)

    # Convert to grayscale
    gray = resized.convert('L')

    # Apply Atkinson dithering
    dithered = atkinson_dither(gray, threshold)

    # Create output image with black background
    output = Image.new('1', (target_width, target_height), 1)

    # Invert so white pixels become 1 (black on e-paper) and black become 0 (white on e-paper)
    inverted = ImageOps.invert(dithered)

    # Center the image
    x_offset = (target_width - new_width) // 2
    y_offset = (target_height - new_height) // 2
    output.paste(inverted, (x_offset, y_offset))

    return output


def create_animation_files(input_gif, output_c, output_h, name="new_animation",
                           target_width=160, target_height=68, threshold=128):
    """Create C and H files for animation from GIF."""
    img = Image.open(input_gif)
    frame_count = img.n_frames

    # Generate C file
    c_content = f'''/* Generated using gif-convert.py */
/* Contains {frame_count} image(s). */
#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

'''

    # Add attribute guards
    for i in range(frame_count):
        frame_name = f"{name}_{i:02d}"
        c_content += f'''#ifndef LV_ATTRIBUTE_IMG_{frame_name.upper()}
#define LV_ATTRIBUTE_IMG_{frame_name.upper()}
#endif

'''

    # Process each frame
    for frame_idx in range(frame_count):
        img.seek(frame_idx)
        frame = img.convert('RGB')

        # Apply Atkinson dithering
        processed = process_frame(frame, target_width, target_height, threshold)

        # Get frame data
        frame_data = processed.tobytes()
        data_size = len(frame_data) + 8

        frame_name = f"{name}_{frame_idx:02d}"
        c_content += f'''// Autogenerated map from frame {frame_idx}
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_{frame_name.upper()} uint8_t {frame_name}_map[] =
{{
  0x00, 0x00, 0x00, 0xff, /*Color of index 0 (black)*/
  0xff, 0xff, 0xff, 0xff, /*Color of index 1 (white)*/

'''

        # Write frame data
        for i, byte in enumerate(frame_data):
            if i % 16 == 0:
                c_content += "    "
            c_content += f"0x{byte:02X}, "
            if (i + 1) % 16 == 0:
                c_content += "\n"
        if len(frame_data) % 16 != 0:
            c_content += "\n"

        c_content += f'''}};

const lv_img_dsc_t {frame_name} = {{
  .header.cf = LV_IMG_CF_INDEXED_1BIT,
  .header.always_zero = 0,
  .header.reserved = 0,
  .header.w = {target_width},
  .header.h = {target_height},
  .data_size = {data_size},
  .data = {frame_name}_map,
}};

'''

    # Generate H file
    h_content = f'''#ifndef {name.upper()}_IMAGES_H
#define {name.upper()}_IMAGES_H
#ifdef __cplusplus
extern "C" {{
#endif
#include "lvgl.h"
// -------- Image Descriptors Declarations --------
'''

    for i in range(frame_count):
        frame_name = f"{name}_{i:02d}"
        h_content += f'LV_IMG_DECLARE({frame_name});\n'

    h_content += f'''
// -------- Array of Pointers to Image Descriptors --------
const lv_img_dsc_t *{name}_images[{frame_count}] = {{
'''

    for i in range(frame_count):
        frame_name = f"{name}_{i:02d}"
        h_content += f'    &{frame_name},\n'

    h_content += f'''}};

#define {name.upper()}_IMAGES_NUM_IMAGES {frame_count}

#ifdef __cplusplus
}} /* extern "C" */
#endif
#endif /* {name.upper()}_IMAGES_H */
'''

    # Write files
    with open(output_c, 'w') as f:
        f.write(c_content)

    with open(output_h, 'w') as f:
        f.write(h_content)

    return frame_count


def preprocess_gif_with_imagemagick(input_gif, output_gif, crop=None, rotate=None, center=False):
    """Preprocess GIF using ImageMagick to coalesce frames and convert to grayscale.

    Args:
        input_gif: Path to input GIF file
        output_gif: Path for preprocessed output
        crop: Optional crop geometry (e.g., "160x68" or "160x68+0+0")
        rotate: Optional rotation angle in degrees (default: None)
        center: Whether to center the crop using -gravity center (default: False)

    The order of operations is: coalesce → rotate → colorspace Gray → gravity center → crop → +repage
    """
    try:
        cmd = [
            "magick",
            input_gif,
            "-coalesce",
        ]

        # Add rotation if specified
        if rotate is not None:
            cmd.extend(["-rotate", str(rotate)])

        # Convert to grayscale
        cmd.extend(["-colorspace", "Gray"])

        # Add gravity center BEFORE crop if center is requested
        if center:
            cmd.extend(["-gravity", "center"])

        # Add crop if specified (must come after gravity for centering to work)
        if crop:
            # If crop doesn't include offset, add +0+0
            if '+' not in crop:
                cmd.extend(["-crop", f"{crop}+0+0"])
            else:
                cmd.extend(["-crop", crop])
            cmd.append("+repage")

        cmd.append(output_gif)

        subprocess.run(cmd, check=True, capture_output=True, text=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f"ImageMagick error: {e.stderr}")
        return False
    except FileNotFoundError:
        print("ImageMagick 'magick' command not found. Please install ImageMagick.")
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Convert GIF to ZMK nice!view animation using Atkinson dithering.\n"
                    "Output goes to boards/shields/eyelash_sofle_animation/assets/ by default.\n"
                    "Always use --no-register; update CMakeLists.txt and custom_status_screen.c manually."
    )
    parser.add_argument(
        "input_gif",
        help="Path to the input GIF file"
    )
    parser.add_argument(
        "-n", "--name",
        help="Base name for output files (default: derived from GIF filename without extension)",
        default=None
    )
    parser.add_argument(
        "-o", "--output-dir",
        help=f"Output directory for generated .c and .h files (default: {DEFAULT_ASSETS_DIR})",
        default=DEFAULT_ASSETS_DIR
    )
    parser.add_argument(
        "-W", "--width",
        type=int,
        default=160,
        help="Target width in pixels (default: 160 — full nice!view width)"
    )
    parser.add_argument(
        "-H", "--height",
        type=int,
        default=68,
        help="Target height in pixels (default: 68 — full nice!view height)"
    )
    parser.add_argument(
        "-r", "--rotate",
        type=int,
        default=None,
        help="Rotation angle in degrees for ImageMagick (default: no rotation)"
    )
    parser.add_argument(
        "--center",
        action="store_true",
        help="Set image gravity to center"
    )
    parser.add_argument(
        "-c", "--crop",
        help="Crop geometry for ImageMagick (e.g., '160x68' or '160x68+0+0')"
    )
    parser.add_argument(
        "--no-preprocess",
        action="store_true",
        help="Skip ImageMagick preprocessing (useful if GIF is already preprocessed)"
    )
    parser.add_argument(
        "-t", "--threshold",
        type=int,
        default=128,
        help="Dithering threshold (0-255, default: 128)"
    )
    parser.add_argument(
        "-ms", "--animation-ms",
        type=int,
        default=3000,
        help="Animation duration hint in ms (for reference; set EYELASH_ANIM_MS in Kconfig)"
    )
    parser.add_argument(
        "--no-register",
        action="store_true",
        default=True,
        help="Skip auto-registration (default: True — always use --no-register)"
    )

    args = parser.parse_args()

    # Derive name from filename if not provided
    name = args.name
    if name is None:
        name = os.path.splitext(os.path.basename(args.input_gif))[0]
        # Sanitize: replace hyphens and spaces with underscores
        name = re.sub(r'[^a-zA-Z0-9_]', '_', name)

    input_gif = args.input_gif
    output_dir = args.output_dir

    os.makedirs(output_dir, exist_ok=True)

    # Preprocess with ImageMagick unless skipped
    if not args.no_preprocess:
        print(f"Preprocessing {input_gif} with ImageMagick...")
        with tempfile.NamedTemporaryFile(suffix=".gif", delete=False) as tmp:
            tmp_path = tmp.name
        rotate_value = args.rotate
        if preprocess_gif_with_imagemagick(input_gif, tmp_path, crop=args.crop,
                                            rotate=rotate_value, center=args.center):
            input_gif = tmp_path
            print("Preprocessing complete.")
        else:
            print("Preprocessing failed, using original GIF.")

    print(f"Processing {input_gif}...")
    count = create_animation_files(
        input_gif,
        os.path.join(output_dir, f"{name}.c"),
        os.path.join(output_dir, f"{name}.h"),
        name=name,
        target_width=args.width,
        target_height=args.height,
        threshold=args.threshold
    )
    print(f"Generated {count} frames → {output_dir}/{name}.c and {name}.h")
    print()
    print("Next steps:")
    print(f"  1. Edit boards/shields/eyelash_sofle_animation/CMakeLists.txt:")
    print(f"       Replace: zephyr_library_sources(assets/placeholder.c)")
    print(f"       With:    zephyr_library_sources(assets/{name}.c)")
    print(f"  2. Edit boards/shields/eyelash_sofle_animation/custom_status_screen.c:")
    print(f"       Replace: #include \"assets/placeholder.h\"")
    print(f"       With:    #include \"assets/{name}.h\"")
    print(f"     And update the animation source array/count variables accordingly.")
    print(f"  3. Rebuild: run the 'ZMK: WSL build firmware local' task.")

    # Clean up temp file if it was created
    if not args.no_preprocess and 'tmp_path' in locals() and os.path.exists(tmp_path):
        os.unlink(tmp_path)


if __name__ == "__main__":
    main()
